# Configuration Mosquitto pour tests distanciels

# Général
persistence true
persistence_location /mosquitto/data/

# Log
log_dest file /mosquitto/log/mosquitto.log
log_type error
log_type warning
log_type notice
log_type information
log_timestamp true

# Port MQTT standard
listener 1883
protocol mqtt

# Port WebSocket pour les clients web
listener 9001
protocol websockets

# Interdire les connexions anonymes
allow_anonymous false

# Fichier des mots de passe
password_file /mosquitto/config/passwd